version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "20210:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: railway
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    command: sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    ports:
      - "52777:6379"
    env_file:
      - .env

volumes:
  mysql_data:
